/// 工具配置文件
/// 在这里添加新工具，只需添加配置即可
class ToolConfig {
  // 分类配置
  static const categories = [
    {
      'id': 'ai',
      'name': 'AI智能',
      'icon': '🤖',
      'sort': 0,
      'enabled': true,
    },
    {
      'id': 'daily',
      'name': '日常助手',
      'icon': '📅',
      'sort': 1,
      'enabled': true,
    },
    {
      'id': 'dev',
      'name': '开发工具',
      'icon': '💻',
      'sort': 2,
      'enabled': true,
    },
    {
      'id': 'utility',
      'name': '实用工具',
      'icon': '🔧',
      'sort': 3,
      'enabled': true,
    },
  ];

  // 工具配置 - 40个工具
  static const tools = [
    // ========== AI智能 (10个) ==========
    {
      'id': 'ai_chat',
      'categoryId': 'ai',
      'name': 'AI对话',
      'icon': '💬',
      'description': '多模型AI对话助手',
      'route': '/tool/ai_chat',
      'enabled': true,
      'sort': 0,
    },
    {
      'id': 'ai_writing',
      'categoryId': 'ai',
      'name': 'AI写作',
      'icon': '✍️',
      'description': '翻译/摘要/改写/扩写',
      'route': '/tool/ai_writing',
      'enabled': true,
      'sort': 1,
    },
    {
      'id': 'ai_image',
      'categoryId': 'ai',
      'name': 'AI识图',
      'icon': '👁️',
      'description': '图片描述/OCR提取',
      'route': '/tool/ai_image',
      'enabled': true,
      'sort': 2,
    },
    {
      'id': 'ai_paint',
      'categoryId': 'ai',
      'name': 'AI绘画',
      'icon': '🎨',
      'description': 'AI生成图片',
      'route': '/tool/ai_paint',
      'enabled': true,
      'sort': 3,
    },
    {
      'id': 'prompt_library',
      'categoryId': 'ai',
      'name': 'Prompt库',
      'icon': '📝',
      'description': '提示词模板管理',
      'route': '/tool/prompt_library',
      'enabled': true,
      'sort': 4,
    },
    {
      'id': 'ai_voice',
      'categoryId': 'ai',
      'name': 'AI语音',
      'icon': '🎙️',
      'description': '语音转文字/文字转语音',
      'route': '/tool/ai_voice',
      'enabled': true,
      'sort': 5,
    },
    {
      'id': 'ai_code',
      'categoryId': 'ai',
      'name': 'AI代码',
      'icon': '👨‍💻',
      'description': '代码生成/解释/优化',
      'route': '/tool/ai_code',
      'enabled': true,
      'sort': 6,
    },
    {
      'id': 'ai_excel',
      'categoryId': 'ai',
      'name': 'AI表格',
      'icon': '📊',
      'description': 'Excel公式生成/数据分析',
      'route': '/tool/ai_excel',
      'enabled': true,
      'sort': 7,
    },
    {
      'id': 'ai_document',
      'categoryId': 'ai',
      'name': 'AI文档',
      'icon': '📄',
      'description': 'PDF对话/文档摘要',
      'route': '/tool/ai_document',
      'enabled': true,
      'sort': 8,
    },
    {
      'id': 'ai_learn',
      'categoryId': 'ai',
      'name': 'AI学习',
      'icon': '📚',
      'description': '知识问答/概念解释',
      'route': '/tool/ai_learn',
      'enabled': true,
      'sort': 9,
    },
    {
      'id': 'ai_translate',
      'categoryId': 'ai',
      'name': 'AI翻译',
      'icon': '🌐',
      'description': '多语言智能翻译',
      'route': '/tool/ai_translate',
      'enabled': true,
      'sort': 10,
    },

    // ========== 日常助手 (10个) ==========
    {
      'id': 'accounting',
      'categoryId': 'daily',
      'name': '记账本',
      'icon': '💰',
      'description': '收支记录统计',
      'route': '/tool/accounting',
      'enabled': true,
      'sort': 0,
    },
    {
      'id': 'schedule',
      'categoryId': 'daily',
      'name': '日程管理',
      'icon': '📅',
      'description': '待办/纪念日/提醒',
      'route': '/tool/schedule',
      'enabled': true,
      'sort': 1,
    },
    {
      'id': 'notes',
      'categoryId': 'daily',
      'name': '笔记',
      'icon': '📓',
      'description': 'Markdown笔记管理',
      'route': '/tool/notes',
      'enabled': true,
      'sort': 2,
    },
    {
      'id': 'password_gen',
      'categoryId': 'daily',
      'name': '密码生成',
      'icon': '🔐',
      'description': '安全密码生成',
      'route': '/tool/password_gen',
      'enabled': true,
      'sort': 3,
    },
    {
      'id': 'habit_tracker',
      'categoryId': 'daily',
      'name': '习惯打卡',
      'icon': '✅',
      'description': '习惯养成追踪',
      'route': '/tool/habit_tracker',
      'enabled': true,
      'sort': 4,
    },
    {
      'id': 'health_record',
      'categoryId': 'daily',
      'name': '健康记录',
      'icon': '💪',
      'description': '体重/饮水/睡眠记录',
      'route': '/tool/health_record',
      'enabled': true,
      'sort': 5,
    },
    {
      'id': 'reading_notes',
      'categoryId': 'daily',
      'name': '读书笔记',
      'icon': '📖',
      'description': '书籍管理/阅读进度',
      'route': '/tool/reading_notes',
      'enabled': true,
      'sort': 6,
    },
    {
      'id': 'mood_diary',
      'categoryId': 'daily',
      'name': '心情日记',
      'icon': '😊',
      'description': '情绪记录统计',
      'route': '/tool/mood_diary',
      'enabled': true,
      'sort': 7,
    },
    {
      'id': 'shopping_list',
      'categoryId': 'daily',
      'name': '购物清单',
      'icon': '🛒',
      'description': '购物清单管理',
      'route': '/tool/shopping_list',
      'enabled': true,
      'sort': 8,
    },
    {
      'id': 'travel_plan',
      'categoryId': 'daily',
      'name': '旅行计划',
      'icon': '✈️',
      'description': '行程规划与费用管理',
      'route': '/tool/travel_plan',
      'enabled': true,
      'sort': 9,
    },

    // ========== 开发工具 (10个) ==========
    {
      'id': 'json',
      'categoryId': 'dev',
      'name': 'JSON工具',
      'icon': '📋',
      'description': '格式化/压缩/校验',
      'route': '/tool/json',
      'enabled': true,
      'sort': 0,
    },
    {
      'id': 'code_diff',
      'categoryId': 'dev',
      'name': '代码对比',
      'icon': '📝',
      'description': '文本/代码差异对比',
      'route': '/tool/code_diff',
      'enabled': true,
      'sort': 1,
    },
    {
      'id': 'encoding',
      'categoryId': 'dev',
      'name': '编码解码',
      'icon': '🔤',
      'description': 'Base64/URL/Unicode/Hex',
      'route': '/tool/encoding',
      'enabled': true,
      'sort': 2,
    },
    {
      'id': 'regex',
      'categoryId': 'dev',
      'name': '正则测试',
      'icon': '🔍',
      'description': '正则表达式测试',
      'route': '/tool/regex',
      'enabled': true,
      'sort': 3,
    },
    {
      'id': 'time',
      'categoryId': 'dev',
      'name': '时间戳转换',
      'icon': '⏰',
      'description': '时间戳/日期互转',
      'route': '/tool/time',
      'enabled': true,
      'sort': 4,
    },
    {
      'id': 'color_picker',
      'categoryId': 'dev',
      'name': '颜色选择器',
      'icon': '🎨',
      'description': 'RGB/HEX颜色选择',
      'route': '/tool/color_picker',
      'enabled': true,
      'sort': 5,
    },
    {
      'id': 'password_gen',
      'categoryId': 'dev',
      'name': '密码生成器',
      'icon': '🔐',
      'description': '安全随机密码生成',
      'route': '/tool/password_gen',
      'enabled': true,
      'sort': 6,
    },
    {
      'id': 'url_parser',
      'categoryId': 'dev',
      'name': 'URL解析',
      'icon': '🔗',
      'description': 'URL参数解析/重构',
      'route': '/tool/url_parser',
      'enabled': true,
      'sort': 7,
    },
    {
      'id': 'qrcode',
      'categoryId': 'dev',
      'name': '二维码生成',
      'icon': '📱',
      'description': '二维码生成/WiFi分享',
      'route': '/tool/qrcode',
      'enabled': true,
      'sort': 8,
    },
    {
      'id': 'text_diff',
      'categoryId': 'dev',
      'name': '文本对比',
      'icon': '⚖️',
      'description': '文本差异对比工具',
      'route': '/tool/text_diff',
      'enabled': true,
      'sort': 9,
    },
    {
      'id': 'jwt',
      'categoryId': 'dev',
      'name': 'JWT解码',
      'icon': '🔐',
      'description': 'JWT Token解码验证',
      'route': '/tool/jwt',
      'enabled': true,
      'sort': 10,
    },
    {
      'id': 'html_escape',
      'categoryId': 'dev',
      'name': 'HTML转义',
      'icon': '🔤',
      'description': 'HTML实体编码解码',
      'route': '/tool/html_escape',
      'enabled': true,
      'sort': 11,
    },

    // ========== 实用工具 (10个) - v3.2.0完整实现 ==========
    {
      'id': 'unit_convert',
      'categoryId': 'utility',
      'name': '单位换算',
      'icon': '📏',
      'description': '长度/重量/温度等换算',
      'route': '/tool/unit',
      'enabled': true,
      'sort': 0,
    },
    {
      'id': 'calculator',
      'categoryId': 'utility',
      'name': '计算器',
      'icon': '🧮',
      'description': '标准计算器，支持历史',
      'route': '/tool/calculator',
      'enabled': true,
      'sort': 1,
    },
    {
      'id': 'countdown',
      'categoryId': 'utility',
      'name': '倒计时',
      'icon': '⏱️',
      'description': '多个倒计时，后台提醒',
      'route': '/tool/countdown',
      'enabled': true,
      'sort': 2,
    },
    {
      'id': 'random_number',
      'categoryId': 'utility',
      'name': '随机数',
      'icon': '🎲',
      'description': '随机数生成，支持批量',
      'route': '/tool/random_number',
      'enabled': true,
      'sort': 3,
    },
    {
      'id': 'decision',
      'categoryId': 'utility',
      'name': '决策助手',
      'icon': '🎯',
      'description': '随机选择，转盘抽签',
      'route': '/tool/decision',
      'enabled': true,
      'sort': 4,
    },
    {
      'id': 'calendar',
      'categoryId': 'utility',
      'name': '日历查询',
      'icon': '📅',
      'description': '万年历/节假日/农历',
      'route': '/tool/calendar',
      'enabled': true,
      'sort': 5,
    },
    {
      'id': 'exchange_rate',
      'categoryId': 'utility',
      'name': '汇率换算',
      'icon': '💱',
      'description': '多币种汇率换算',
      'route': '/tool/exchange_rate',
      'enabled': true,
      'sort': 6,
    },
    {
      'id': 'bmi',
      'categoryId': 'utility',
      'name': 'BMI计算',
      'icon': '⚖️',
      'description': '身体质量指数计算',
      'route': '/tool/bmi',
      'enabled': true,
      'sort': 7,
    },
    {
      'id': 'mortgage',
      'categoryId': 'utility',
      'name': '房贷计算',
      'icon': '🏠',
      'description': '等额本息/等额本金',
      'route': '/tool/mortgage',
      'enabled': true,
      'sort': 8,
    },
    {
      'id': 'network_speed',
      'categoryId': 'utility',
      'name': '网速测试',
      'icon': '📡',
      'description': '下载/上传速度测试',
      'route': '/tool/network_speed',
      'enabled': true,
      'sort': 9,
    },

    // ========== 扩展工具 - v3.2.1新增 ==========
    {
      'id': 'weather',
      'categoryId': 'utility',
      'name': '天气查询',
      'icon': '🌤️',
      'description': '实时天气/未来预报',
      'route': '/tool/weather',
      'enabled': true,
      'sort': 10,
    },
    {
      'id': 'world_clock',
      'categoryId': 'utility',
      'name': '世界时钟',
      'icon': '🌍',
      'description': '多时区时钟显示',
      'route': '/tool/world_clock',
      'enabled': true,
      'sort': 11,
    },
    {
      'id': 'phone_lookup',
      'categoryId': 'utility',
      'name': '手机号归属地',
      'icon': '📞',
      'description': '查询手机号码归属地',
      'route': '/tool/phone_lookup',
      'enabled': true,
      'sort': 12,
    },
    {
      'id': 'image_tool',
      'categoryId': 'utility',
      'name': '图片工具',
      'icon': '🖼️',
      'description': '图片压缩/裁剪/转换',
      'route': '/tool/image',
      'enabled': true,
      'sort': 13,
    },
    {
      'id': 'network_tool',
      'categoryId': 'dev',
      'name': '网络工具',
      'icon': '🌐',
      'description': 'Ping/IP查询/端口扫描',
      'route': '/tool/network',
      'enabled': true,
      'sort': 12,
    },
    {
      'id': 'http_test',
      'categoryId': 'dev',
      'name': 'HTTP测试',
      'icon': '📤',
      'description': 'API接口调试工具',
      'route': '/tool/http_test',
      'enabled': true,
      'sort': 13,
    },
    {
      'id': 'git_command',
      'categoryId': 'dev',
      'name': 'Git命令',
      'icon': '🌲',
      'description': 'Git命令速查手册',
      'route': '/tool/git_command',
      'enabled': true,
      'sort': 14,
    },
    {
      'id': 'code_format',
      'categoryId': 'dev',
      'name': '代码格式化',
      'icon': '✨',
      'description': 'JSON/XML/HTML格式化',
      'route': '/tool/code_format',
      'enabled': true,
      'sort': 15,
    },
    {
      'id': 'data_backup',
      'categoryId': 'daily',
      'name': '数据备份',
      'icon': '💾',
      'description': '导出/导入应用数据',
      'route': '/tool/data_backup',
      'enabled': true,
      'sort': 10,
    },
    {
      'id': 'notes',
      'categoryId': 'daily',
      'name': 'Markdown笔记',
      'icon': '📝',
      'description': 'Markdown富文本笔记',
      'route': '/tool/notes',
      'enabled': true,
      'sort': 11,
    },
  ];

  /// 获取指定分类的工具列表
  static List<Map<String, dynamic>> getToolsByCategory(String categoryId) {
    return tools
        .where((tool) => tool['categoryId'] == categoryId && tool['enabled'] == true)
        .toList()
      ..sort((a, b) => (a['sort'] as int).compareTo(b['sort'] as int));
  }

  /// 获取所有启用的分类
  static List<Map<String, dynamic>> getEnabledCategories() {
    return categories
        .where((cat) => cat['enabled'] == true)
        .toList()
      ..sort((a, b) => (a['sort'] as int).compareTo(b['sort'] as int));
  }
}
